### PR TITLE
fix compilation in Kinetic (c++14) and add (partially) option --all

### PR DESCRIPTION
**Pull request by facontidavide**
Important: option -all is incomplete: we must add the ability to add
dynamically subscribers once they are published.

### CODE REVIEW

**Comment by facontidavide** [comment]
Related to #4

**Comment by facontidavide** [comment]
After inspecting the code, I realized that implementing correctly the option -all will be a considerable amount of work, since not only the main but also other classes need to be refactored. nevertheless, I think it is worth it!

My suggestion is to merge into one the classes TopicManager and TopicSubscriber, because their decoupling make it harder to deal with the internal state (list of topics).

I don't have much time to do this myself... maybe in the future ;)

**Comment by xqms** [comment]
Thanks for the PR!

 * You have a lot of whitespace changes since I'm using tabs for indentation in this project. While it should probably be changed to spaces, that should be a separate process. Please use tabs in the meanwhile!
 * I'm not sure I'm willing to go to C++14 just to support Kinetic (nobody is using it in our lab). But I'll think about that one more. A separate PR would be better.
 * `--all`: From my experience, `--all` is usually dangerous when used in a system with cameras - `image_transport` will result in a lot of redundant topics which results in a lot of bandwidth and computation overhead. Do you have an idea on how to improve this?

Yes, probably the internal architecture is not well suited for a dynamic `--all`. I designed it with the exact opposite use case in mind (someone specifies a topic that is not there - and we need to display and warn the user). It's also a bit more decoupled to allow a later `play` command to use the same infrastructure.

**Comment by facontidavide** [comment]
Ok, as you wish. But I think you should support kinetic... we are lot of people 😀. 

I will change this pr to do that only

**Pull request closed without merging**
