### PR TITLE
Automatic cleanup of bag folder and bag size limit

### PR DESCRIPTION
**Pull request by JanQuenzel**
…g size.

### CODE REVIEW

**Comment by xqms** [comment]
Thanks! Some issues I see that we should fix before merging:

 * [ ] The `directory-cleanup-size` should be usable without `start-stop-bag-size`. That means we should periodically check the directory size, not only on start/stop. Special care needs to be taken to not interrupt the recording (e.g. use a second thread for deletion).
 * [ ] Parse SI suffixes such as KB/MB/GB for the size options
 * [ ] Maybe rename `--directory-cleanup-size=10GB` to `delete-old-at=10GB`?
 * [ ] Maybe rename `--start-stop-bag-size` to `--max-file-size`?

**Comment by JanQuenzel** [comment]
`--start-stop-bag-size` has been renamed to `--split-bag-size`.
`--directory-cleanup-size` has been renamed  to `--delete-old-at`.
The deletion of old bags has now moved into a new thread with periodic checking independent of splitting the bag.
Parsing of SI suffixes like mb/mib/MB/MiB etc. has been added from bytes up to TiB.

**Comment by xqms** [comment]
@ros-pull-request-builder retest this please

**Comment by xqms** [comment]
Rebased on master. I'll look at the remaining points now :)

**Pull request merged**
